### ISSUE TITLE
'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by enricodvn** [mattupstate/flask-jwt#143]
Seems related to https://github.com/jpadilla/pyjwt/issues/529

Getting this error after the new dependency resolver on pip 20.3.

**Comment by enricodvn** [comment]
To fix that I had to fix the pyjwt version on the requirements. Working with `pyjwt==1.7.1`
